### ISSUE TITLE
Dockerfile optimization

### ISSUE THREAD

**Issue by jklingen92** [IndicoDataSolutions/virga#14]
For local development, docker's caching properties aren't being taken advantage of. This is true in every dockerfile that I saw:

```
# copy codebase to container with developer owner
COPY --chown=developer . /home/developer/$app_name
WORKDIR /home/developer/$app_name

USER developer

# install app dependencies
RUN yarn install
```
should be changed to something like this:
```
# copy requirements files to container
COPY package.json yarn.lock /home/developer/$app_name/

# install app dependencies
RUN yarn install

# copy requirements files to container
COPY . /home/developer/$app_name/
```
I would put in a PR myself but I don't understand the significance of the developer user that's created. The presence of that user makes it impossible to install node_modules completely (probably for permissions reasons). Similarly, snowpack and poetry have problems when you try to perform operations outside of the scope of the developer.

**Comment by thearchitector** [comment]
The `developer` user was added to allow host-container editing of container-generated files (primarily `node_modules`) with a named user. It was an artifact of the old development cycle, which has been thrown out in favor of a new one, so the `developer` user will no longer exist in the next update.

The update will also harden container images for production, which involves correctly caching dependencies like you point out above.
